from fvm import FvmFramework

fvm = FvmFramework()
fvm.add_vhdl_source("examples/counter/counter.vhd")
fvm.set_toplevel("counter")
fvm.add_config("counter", "max_count_4", dict(MAX_COUNT=4))
fvm.add_config("counter", "max_count_8", dict(MAX_COUNT=8))
fvm.add_config("counter", "max_count_16", dict(MAX_COUNT=16))
fvm.add_config("counter", "max_count_32", dict(MAX_COUNT=32))
fvm.add_config("counter", "max_count_64", dict(MAX_COUNT=64))
fvm.add_config("counter", "max_count_128", dict(MAX_COUNT=128))
fvm.set_coverage_goal("reachability", 40)
fvm.skip("lint")
fvm.skip("friendliness")
fvm.skip("rulecheck")
fvm.skip("xverify")
fvm.skip("resets")
fvm.skip("clocks")
fvm.skip("prove")
fvm.run()
